{
  /* <map name="mathmap">
          <area
            shape="rect"
            coords="50,599,120,520"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="300,590,370,505"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="260,370,330,300"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="300,190,370,120"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="520,130,595,70"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="750,140,830,70"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="920,250,990,180"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="855,420,920,350"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="700,590,770,520"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="630,750,710,690"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="750,870,820,810"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="1030,830,1100,760"
            alt="Computer"
            href="/mathworksheet"
          />
          <area
            shape="rect"
            coords="1140,600,1200,530"
            alt="Computer"
            href="/mathworksheet"
          />
        </map> */
}
